version: '3'

services:
  mysqldb:
    container_name: dbcontainer
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'kurswahldb'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    networks:
      - springmysql-net
    ports:
      - '3360:3306'
    restart: always
    volumes:
      - my-db:/var/lib/mysql
  backend:
    container_name: backendcontainer
    build: ./kurswahl
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/kurswahldb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: '${DB_PASSWORD}'
      SPRING_JPA_DATABASE-PLATFORM: 'org.hibernate.dialect.MySQL5InnoDBDialect'
      SPRING_APPLICATION_JSON: '{
              bezkoder.app.jwtSecret: ${JWT_SECRET}
            }'
    volumes:
      - './kurswahl:/usr/src/app'
    ports:
      - '8008:8080'
    networks:
      - springmysql-net
      - backend
      - nginx_backend
    restart: always
    depends_on:
      - mysqldb
  frontend:
    container_name: frontendcontainer
    build: ./kurswahl-ui
    volumes:
      - './kurswahl-ui:/usr/src/app'
    restart: always
    depends_on:
      - backend
    networks:
      - backend
      - nginx_backend
    ports:
      - '4300:80'

networks:
  springmysql-net:
  backend:
  nginx_backend:
    external: true


volumes:
  my-db: