version: '3'

services:
  mysqldb:
    container_name: kurswahl_dbcontainer
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'kurswahldb'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD_KURSWAHL}'
    networks:
      - db-backend
    ports:
      - '3360:3306'
    restart: always
    volumes:
      - './kurswahl-db:/var/lib/mysql'
  backend:
    container_name: kurswahl_backendcontainer
    build: ./kurswahl
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/kurswahldb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: '${DB_PASSWORD_KURSWAHL}'
      BEZKODER_APP_JWTSECRET: '${JWT_SECRET}'
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECt: 'org.hibernate.dialect.MySQLDialect'
    volumes:
      - './kurswahl:/usr/src/app'
    ports:
      - '8008:8080'
    networks:
      - db-backend
      - backend-frontend
    restart: always
    depends_on:
      - mysqldb
  frontend:
    container_name: kurswahl_frontendcontainer
    build: ./kurswahl-ui
    volumes:
      - './kurswahl-ui:/usr/src/app'
    restart: always
    depends_on:
      - backend
    networks:
      - backend-frontend
    ports:
      - '4300:80'

networks:
  db-backend:
  backend-frontend:

volumes:
  kurswahl-db: