name: Kurswahl Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven
      - name: Build and Test with Maven
        run: mvn -B package --file kurswahl/pom.xml
  deploy:
    name: Deployment
    runs-on: self-hosted
    needs:
      - build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        # if: github.event_name != 'pull_request'
      - name: Start docker-compose
        run: |
          docker-compose down
          docker-compose up --build -d
        # if: github.event_name != 'pull_request'
